# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CourseModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CourseModel.proto',
  package='m.studyduniya.com.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x43ourseModel.proto\x12\x17m.studyduniya.com.proto\"G\n\tFullProto\x12:\n\x07\x63ourses\x18\x01 \x03(\x0b\x32).m.studyduniya.com.proto.CourseModelProto\"v\n\x10\x43ourseModelProto\x12\x10\n\x08\x63ourseID\x18\x01 \x01(\x05\x12\x12\n\ncourseName\x18\x02 \x01(\t\x12<\n\x08subjects\x18\x03 \x03(\x0b\x32*.m.studyduniya.com.proto.SubjectModelProto\"u\n\x11SubjectModelProto\x12\x11\n\tsubjectID\x18\x01 \x01(\x05\x12\x13\n\x0bsubjectName\x18\x02 \x01(\t\x12\x38\n\x06topics\x18\x03 \x03(\x0b\x32(.m.studyduniya.com.proto.TopicModelProto\"\xe2\x01\n\x0fTopicModelProto\x12\x0f\n\x07topicID\x18\x01 \x01(\x05\x12\x11\n\ttopicName\x18\x02 \x01(\t\x12\x39\n\x06videos\x18\x03 \x03(\x0b\x32).m.studyduniya.com.proto.VideosModelProto\x12\x39\n\x06\x65\x62ooks\x18\x04 \x03(\x0b\x32).m.studyduniya.com.proto.EbooksModelProto\x12\x35\n\x04mcqs\x18\x05 \x03(\x0b\x32\'.m.studyduniya.com.proto.MCQsModelProto\"c\n\x10VideosModelProto\x12\x10\n\x08videoUID\x18\x01 \x01(\t\x12\x11\n\tvideoName\x18\x02 \x01(\t\x12\x18\n\x10videoDescription\x18\x03 \x01(\t\x12\x10\n\x08videoURL\x18\x04 \x01(\t\"~\n\x10\x45\x62ooksModelProto\x12\x10\n\x08\x65\x62ookUID\x18\x01 \x01(\t\x12\x11\n\tebookName\x18\x02 \x01(\t\x12\x18\n\x10\x65\x62ookDescription\x18\x03 \x01(\t\x12\x10\n\x08\x65\x62ookURL\x18\x04 \x01(\t\x12\x19\n\x11\x65\x62ookThumbnailUID\x18\x05 \x01(\t\"\x91\x01\n\x0eMCQsModelProto\x12\x0e\n\x06mcqUID\x18\x01 \x01(\t\x12\x1a\n\x12isMcqSingleCorrect\x18\x02 \x01(\x08\x12\x13\n\x0bmcqQuestion\x18\x03 \x01(\t\x12\x12\n\nmcqOptions\x18\x04 \x03(\t\x12\x15\n\tmcqAnswer\x18\x05 \x03(\x08\x42\x02\x10\x01\x12\x13\n\x0bmcqSolution\x18\x06 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FULLPROTO = _descriptor.Descriptor(
  name='FullProto',
  full_name='m.studyduniya.com.proto.FullProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='courses', full_name='m.studyduniya.com.proto.FullProto.courses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=117,
)


_COURSEMODELPROTO = _descriptor.Descriptor(
  name='CourseModelProto',
  full_name='m.studyduniya.com.proto.CourseModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='courseID', full_name='m.studyduniya.com.proto.CourseModelProto.courseID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='courseName', full_name='m.studyduniya.com.proto.CourseModelProto.courseName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subjects', full_name='m.studyduniya.com.proto.CourseModelProto.subjects', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=237,
)


_SUBJECTMODELPROTO = _descriptor.Descriptor(
  name='SubjectModelProto',
  full_name='m.studyduniya.com.proto.SubjectModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subjectID', full_name='m.studyduniya.com.proto.SubjectModelProto.subjectID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subjectName', full_name='m.studyduniya.com.proto.SubjectModelProto.subjectName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topics', full_name='m.studyduniya.com.proto.SubjectModelProto.topics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=356,
)


_TOPICMODELPROTO = _descriptor.Descriptor(
  name='TopicModelProto',
  full_name='m.studyduniya.com.proto.TopicModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topicID', full_name='m.studyduniya.com.proto.TopicModelProto.topicID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topicName', full_name='m.studyduniya.com.proto.TopicModelProto.topicName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='videos', full_name='m.studyduniya.com.proto.TopicModelProto.videos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ebooks', full_name='m.studyduniya.com.proto.TopicModelProto.ebooks', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tests', full_name='m.studyduniya.com.proto.TestModelProto.tests', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mcqs', full_name='m.studyduniya.com.proto.TopicModelProto.mcqs', index=5,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=585,
)


_VIDEOSMODELPROTO = _descriptor.Descriptor(
  name='VideosModelProto',
  full_name='m.studyduniya.com.proto.VideosModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='videoUID', full_name='m.studyduniya.com.proto.VideosModelProto.videoUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='videoName', full_name='m.studyduniya.com.proto.VideosModelProto.videoName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='videoDescription', full_name='m.studyduniya.com.proto.VideosModelProto.videoDescription', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='videoURL', full_name='m.studyduniya.com.proto.VideosModelProto.videoURL', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=587,
  serialized_end=686,
)


_EBOOKSMODELPROTO = _descriptor.Descriptor(
  name='EbooksModelProto',
  full_name='m.studyduniya.com.proto.EbooksModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ebookUID', full_name='m.studyduniya.com.proto.EbooksModelProto.ebookUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ebookName', full_name='m.studyduniya.com.proto.EbooksModelProto.ebookName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ebookDescription', full_name='m.studyduniya.com.proto.EbooksModelProto.ebookDescription', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ebookURL', full_name='m.studyduniya.com.proto.EbooksModelProto.ebookURL', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ebookThumbnailUID', full_name='m.studyduniya.com.proto.EbooksModelProto.ebookThumbnailUID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=688,
  serialized_end=814,
)


_TESTMODELPROTO = _descriptor.Descriptor(
  name='TestModelProto',
  full_name='m.studyduniya.com.proto.TestModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='testUID', full_name='m.studyduniya.com.proto.TestModelProto.testUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),

    _descriptor.FieldDescriptor(
      name='testName', full_name='m.studyduniya.com.proto.TestModelProto.testName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='testDescription', full_name='m.studyduniya.com.proto.TestModelProto.testDescription', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),

  ],

  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=688,
  serialized_end=814,
)
_MCQSMODELPROTO = _descriptor.Descriptor(
  name='MCQsModelProto',
  full_name='m.studyduniya.com.proto.MCQsModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mcqUID', full_name='m.studyduniya.com.proto.MCQsModelProto.mcqUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isMcqSingleCorrect', full_name='m.studyduniya.com.proto.MCQsModelProto.isMcqSingleCorrect', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mcqQuestion', full_name='m.studyduniya.com.proto.MCQsModelProto.mcqQuestion', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mcqOptions', full_name='m.studyduniya.com.proto.MCQsModelProto.mcqOptions', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mcqAnswer', full_name='m.studyduniya.com.proto.MCQsModelProto.mcqAnswer', index=4,
      number=5, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='mcqSolution', full_name='m.studyduniya.com.proto.MCQsModelProto.mcqSolution', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=817,
  serialized_end=962,
)

_FULLPROTO.fields_by_name['courses'].message_type = _COURSEMODELPROTO
_COURSEMODELPROTO.fields_by_name['subjects'].message_type = _SUBJECTMODELPROTO
_SUBJECTMODELPROTO.fields_by_name['topics'].message_type = _TOPICMODELPROTO
_TOPICMODELPROTO.fields_by_name['videos'].message_type = _VIDEOSMODELPROTO
_TOPICMODELPROTO.fields_by_name['ebooks'].message_type = _EBOOKSMODELPROTO
_TOPICMODELPROTO.fields_by_name['tests'].message_type = _TESTMODELPROTO
_TOPICMODELPROTO.fields_by_name['mcqs'].message_type = _MCQSMODELPROTO
DESCRIPTOR.message_types_by_name['FullProto'] = _FULLPROTO
DESCRIPTOR.message_types_by_name['CourseModelProto'] = _COURSEMODELPROTO
DESCRIPTOR.message_types_by_name['SubjectModelProto'] = _SUBJECTMODELPROTO
DESCRIPTOR.message_types_by_name['TopicModelProto'] = _TOPICMODELPROTO
DESCRIPTOR.message_types_by_name['VideosModelProto'] = _VIDEOSMODELPROTO
DESCRIPTOR.message_types_by_name['EbooksModelProto'] = _EBOOKSMODELPROTO
DESCRIPTOR.message_types_by_name['TestModelProto'] = _TESTMODELPROTO
DESCRIPTOR.message_types_by_name['MCQsModelProto'] = _MCQSMODELPROTO

FullProto = _reflection.GeneratedProtocolMessageType('FullProto', (_message.Message,), dict(
  DESCRIPTOR = _FULLPROTO,
  __module__ = 'CourseModel_pb2'
  # @@protoc_insertion_point(class_scope:m.studyduniya.com.proto.FullProto)
  ))
_sym_db.RegisterMessage(FullProto)

CourseModelProto = _reflection.GeneratedProtocolMessageType('CourseModelProto', (_message.Message,), dict(
  DESCRIPTOR = _COURSEMODELPROTO,
  __module__ = 'CourseModel_pb2'
  # @@protoc_insertion_point(class_scope:m.studyduniya.com.proto.CourseModelProto)
  ))
_sym_db.RegisterMessage(CourseModelProto)

SubjectModelProto = _reflection.GeneratedProtocolMessageType('SubjectModelProto', (_message.Message,), dict(
  DESCRIPTOR = _SUBJECTMODELPROTO,
  __module__ = 'CourseModel_pb2'
  # @@protoc_insertion_point(class_scope:m.studyduniya.com.proto.SubjectModelProto)
  ))
_sym_db.RegisterMessage(SubjectModelProto)

TopicModelProto = _reflection.GeneratedProtocolMessageType('TopicModelProto', (_message.Message,), dict(
  DESCRIPTOR = _TOPICMODELPROTO,
  __module__ = 'CourseModel_pb2'
  # @@protoc_insertion_point(class_scope:m.studyduniya.com.proto.TopicModelProto)
  ))
_sym_db.RegisterMessage(TopicModelProto)

VideosModelProto = _reflection.GeneratedProtocolMessageType('VideosModelProto', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOSMODELPROTO,
  __module__ = 'CourseModel_pb2'
  # @@protoc_insertion_point(class_scope:m.studyduniya.com.proto.VideosModelProto)
  ))
_sym_db.RegisterMessage(VideosModelProto)

EbooksModelProto = _reflection.GeneratedProtocolMessageType('EbooksModelProto', (_message.Message,), dict(
  DESCRIPTOR = _EBOOKSMODELPROTO,
  __module__ = 'CourseModel_pb2'
  # @@protoc_insertion_point(class_scope:m.studyduniya.com.proto.EbooksModelProto)
  ))
_sym_db.RegisterMessage(EbooksModelProto)

TestModelProto = _reflection.GeneratedProtocolMessageType('TestModelProto', (_message.Message,), dict(
  DESCRIPTOR = _MCQSMODELPROTO,
  __module__ = 'CourseModel_pb2'
  # @@protoc_insertion_point(class_scope:m.studyduniya.com.proto.MCQsModelProto)
))
_sym_db.RegisterMessage(TestModelProto)

MCQsModelProto = _reflection.GeneratedProtocolMessageType('MCQsModelProto', (_message.Message,), dict(
  DESCRIPTOR = _MCQSMODELPROTO,
  __module__ = 'CourseModel_pb2'
  # @@protoc_insertion_point(class_scope:m.studyduniya.com.proto.MCQsModelProto)
  ))
_sym_db.RegisterMessage(MCQsModelProto)


_MCQSMODELPROTO.fields_by_name['mcqAnswer'].has_options = True
_MCQSMODELPROTO.fields_by_name['mcqAnswer']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
